development:
  mysql_username: "root"
  mysql_password:
  mysql_host: "localhost"
  mysql_port: "3306"

test:
  mysql_username: "root"
  mysql_password:
  mysql_host: "localhost"
  mysql_port: "3306"
